### PR TITLE
Add users, languages and skills

### PR DESCRIPTION
**Pull request by sixofhearts**
I basically just created the models and associated them to each other.

A few things that we have to figure out organizationally:

* Which languages should we ask students and teachers that they know?
  * A few (English, German) or all?

* What kinds of skills should teachers have?
  * Is it specific stuff, e.g. jQuery, or is it general, e.g. Development? Is it somewhere between?

### CODE REVIEW

**Comment by gloeglm** [comment]
The tests are all autogenerated? Shouldn't there be at least something in there?

**Comment by sixofhearts** [comment]
All autogenerated. The only thing I've added to the models are Rails-specific features, so we shouldn't have to test that in our Rails app, since it should be tested in the library itself.

**Comment by gloeglm** [comment]
why even have the test files then? can't they just be deleted?

**Comment by sixofhearts** [comment]
Good point. I like having it because we'll eventually have to write methods that we'd like to test - let's give it a home right now. Doesn't have to be this way though.

**Comment by sixofhearts** [comment]
Okay, gonna change the schema per request from @westonhankins to add:

`tech_level` to users
`description` to skills
`level` to language

**Comment by sixofhearts** [comment]
We decided to change the skill name to `text` instead of adding `description` so that there aren't too many fields for the user to think about

**Comment by westonhankins** [comment]
This is perfect! Just like we discussed on the whiteboard.

**Pull request merged**
